### ISSUE TITLE
Hardware Secure Module on RaspberryPi for Raspiblitz

### ISSUE THREAD

**Issue by cedricwalter** [raspiblitz/raspiblitz#1044]
I opened a request at https://github.com/lightningnetwork/lnd/issues/4022  please upvote there. The more vote the better!

**Comment by openoms** [comment]
Instead of adding more closed source components to the Raspberry Pi we should focus on making it as open and verifiable as possible. See this issue about the now programmable EEPROM for example: https://github.com/rootzoll/raspiblitz/issues/818

Even better would be to make a fully open source hardware platform compatible (like RISC-V), but as that seems to be rather far away it is good to ensure compatibility with other platforms such as Hardkernel Odroid and Pine64 products.

Introducing a Raspberry Pi exclusive component would not help with this cause.
