### ISSUE TITLE
Slow final blockchain sync

### ISSUE THREAD

**Issue by osilloh** [raspiblitz/raspiblitz#121]
FTP download completed in less than a day, that seems really quick, is this normal? 

****************************************************
Monitoring Screen Session: Download
Progress: 114.10% (253304616 of 222000000)
If needed press key x to stop Download
NOTICE: This can take multiple hours or days !!
Its OK to close terminal now and SSH back in later.
****************************************************
w0189aba.kasserver. 100%[++++++++++++++++++++] 128.00M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.82M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.84M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.97M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.58M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.95M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.98M  --.-KB/s    in 0s
w0189aba.kasserver. 100%[++++++++++++++++++++] 127.99M  --.-KB/s    in 0s

x !! had to terminate here manually by hitting 'x' key

Final sync has been running for nearly 2 days (I believe it started around .997xxx), and appears to be counting down to zero (decrementing .001 in nearly 48hrs)? Is this normal behavior, it will take 2,000 days at this pace. I restored the wallet I used in my Raspibolt build attempt, it already had testnet coins in them. Is that an issue?

<img width="562" alt="slow final sync" src="https://user-images.githubusercontent.com/40921996/46002398-abaa2400-c049-11e8-9507-bdd55277d8b2.png">

**Comment by rootzoll** [comment]
To download around 200GB from an FTP within a day should be no magic in our internet days. Good to hear that the new FTP server seems to perform. With more users making downloads this is expected to get slower at one point, but for now this looks good.

The long taking final sync is due to an old version of the blockchain state. This should be fixed with #127 hopefully. But will be just a short time solution, because the older the preloaded blockchain gets on the server - the longer the final sync will take and the raspi is really slow on catching up.

In the future it would be good to have two ftp accounts to switch as they get updated. But not sure if possible to reach this already for version 1.0 release - keep fingers crossed.
