### ISSUE TITLE
Power off button + "repair"

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#122]
I recommend a "shutdown button": Options: shutdown, power off, reboot.

If you just pull the plug it can lead to broken tx database. then bitcoind may start, but run into the broken database and restart again and again. On the screen you see bitcoin running, but never any percentage syncing! lnd never starts anyway.

so also a "repair" option was a good feature, with which you can force bitcoin to "-reindex", respectively -reindex-chainstate

Both for me a "must-have" in a version 1.0 with an webinterface. The earlier, the better.

**Comment by machasm1** [comment]
Would concur on a repair function.
Also an orderly shutdown process, so an option in the main menu to shut down the node.
This could issue a lncli stop and bitcoin-cli stop function to shut down the database in an orderly fashion.
Finally issuing a halt to prevent the machine from restarting the daemon.

**Comment by rootzoll** [comment]
Shutdown option in main menu is a good idea. Also a repair option can be placed there. Those two thing a will put on the list for version 1.0 milestone.

Webinterface is something that I plan for a later version, because it should become a bigger replacement for the SSH/terminal anyway. Getting this into 1.0 would delay release too long. Keep in mind that 1.0 release aims to be still a realease for hacky people that can handle SSH/terminal and want a box to build stuff with and experiment. 

Towards Version 2.0 will aim for less techsavy audience that wants control from a webbrower. Also with that switch it makes sense to switch/add to ePaper Display with Buttons for basic interaction like shutdown directly on the device.

**Comment by geco91** [comment]
Shutdown option is now part of the main menu.

@rootzoll Repair would be a nice-2-have for version 1.0 - but would recommend to remove from milestone if time gets an issue.

**Comment by rootzoll** [comment]
There is a new issue about the repair option:
https://github.com/rootzoll/raspiblitz/issues/141

So closing this issue.
