### ISSUE TITLE
Blitz setup won't allow me to supply a cloned blockchain ssd drive during setup

### ISSUE THREAD

**Issue by Swissnode** [raspiblitz/raspiblitz#1267]
Hi,

I used a disk cloner to copy the contents of a RaspiBolt external drive onto a new drive. The following is from the commandline of my Blitz. I had to cancel the setup, as I answered "no" to formatting the ssd drive
```
admin@raspberrypi:/mnt/ext $ ls -la
total 2097192
drwxr-xr-x 6 bitcoin bitcoin       4096 Apr 10 15:23 .
drwxr-xr-x 3 root    root          4096 Jun 19 16:19 ..
drwxr-xr-x 5 bitcoin bitcoin       4096 Jun 18 22:09 bitcoin
drwxr-xr-x 4 bitcoin bitcoin       4096 Jun 11 08:10 lnd
drwx------ 2 bitcoin bitcoin      16384 Oct  3  2019 lost+found
drwxrwx--- 2 lightdm lightdm       4096 Apr 10 15:23 redis
-rw------- 1 bitcoin bitcoin 2147483648 Oct  3  2019 swapfile
```
```
admin@raspberrypi:/mnt/ext $ lsblk -o NAME,MOUNTPOINT,FSTYPE,SIZE
NAME        MOUNTPOINT FSTYPE   SIZE
sda         /mnt/ext   ext4   931.5G
mmcblk0                        59.5G
├─mmcblk0p1 /boot      vfat     256M
└─mmcblk0p2 /          ext4     7.1G
```
So here is the question: how can i carry out the setup of the Blitz but teach it that I already have the blockchain on the external drive? I don't want to use any of the sync options given, as I can clone the 1TB drive in one hour which is my preferred copying method.

Currently I don't know how to continue the setup...

Any help would be great, thanks!

SwissNode

**Comment by openoms** [comment]
Copying the answer from TG here:

The disk needs to be reformatted due to wrong partitioning. The cloner won't help in this case. You will need to copy the bitcoin blocks and chainstate over.

>copying 370GB over the network will not be nice... seeing i have all the data there, there must be some way to achieve it...

Takes about 7h to copy over the network or you could boot a linux and get 2 USB cables as described before.

Cloning the disks to replicate nodes is a problem because of other reasons too. There is data which is unique to your source node. If you open a second node with the same LND wallet all you channels will be force closed and all offchain funds lost.
Duplicating ssh keys would lead to security issues .
