### ISSUE TITLE
IP2Tor Down?

### ISSUE THREAD

**Issue by normandmickey** [raspiblitz/raspiblitz#1389]
Is the IP2Tor Service down? Had IP2Tor working yesterday but cannot get to my DuckDNS domain today.

**Comment by rootzoll** [comment]
In preperation to the final v1.6 release we are closing down the bridge we had running on AWS (which was for testing the relase candidate). Changing the bridge should work like: Go to SUBSCRIBE and List all Subscription - cancel the old IP2TOR Bridge and the setup a new one that directs to the same tor address. Check if your DuckDNS is updating the new IP (if not please report back). The LetsEncrypt should normally stay valid during that process.

**Comment by frennkie** [comment]
Additionally to that there really was a bug in the (re-) activation script: https://github.com/frennkie/django-ip2tor/commit/662d7b9ec1133f509ae7c44f1d95c1d9670da137#diff-a06799e4473b486e72da6187a734011b

So thanks for the info.. 😉

**Comment by normandmickey** [comment]
Thank you.  As far as I can tell it's working now.
BTW, I tried to follow the instructions to self host and things got a
little fuzzy.

Here's where I gave up...
"Thirdly you need to register the Hosts in at least one Shop first to get
the credentials that are needed to retrieve the specific information for
this Host from the Shop database and to make updates (e.g. mark a Bridge as
active).

Don't forget to allow the TCP port ranges on your firewall (both local and
network/cloud based)."

**Comment by frennkie** [comment]
Did you want to setup a `Shop` where people can purchase such Bridges?

Or do you have a VPS and want to use it to host one or two bridges just for yourself?

**Comment by normandmickey** [comment]
To start out I'm just trying to host my own, but i you need more publicly available hosts I would be willing to provide one.

**Comment by frennkie** [comment]
> but i you need more publicly available hosts I would be willing to provide one.

Basically: no

The idea is to get enough people using the Fulmo IP2Tor Shop and paying a few sats so that the virtual machines hosting these are paid for. So if e.g 50 people pay 10 cents a month that would cover the ~ 5€ for a cheap VPS.

If you have a host with a public IPv4 address all you need to host a IP2Tor Bridge yourself is this script: https://github.com/frennkie/django-ip2tor/blob/master/scripts/ip2torc.sh

Feel free to

* run your own bridge with the script, or
* run your own `Shop` with one or more `Bridge Hosts`, or
* use the default Fulmo Shop 

:-)
