### ISSUE TITLE
reboot resets autopilot to 0

### ISSUE THREAD

**Issue by vnnkl** [raspiblitz/raspiblitz#145]
after every reboot the in `lnd.conf` the autopilot is being reset to
```
autopilot.active=0
```

**Comment by geco91** [comment]
The autopilot is the first test for the new raspiblitz settings/config file - see details:
https://github.com/rootzoll/raspiblitz/blob/master/background_raspiblitzSettings.md

At the moment make sure that there is a "autoPilot=on" in the /mnt/hdd/raspiblitz.conf, because this setting gets enforced on every start.

**Comment by geco91** [comment]
@rootzoll on test runs there is a double entry of "autoPilot=on" in the config file. check why.

**Comment by rootzoll** [comment]
yep  - this has to be fixed for version 1.0. I am putting it on the list.

**Comment by rootzoll** [comment]
ok - this is fixed for next release.
