### ISSUE TITLE
re-check for dhcp-server from time to time

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#160]
after a broken internet connection or a broken connection to the dhcp-server in the local network the raspiblictz gets an ip like 169.x.x.x 

you can't connect and get a proper ip again. All you can do is power off, which in many cases leads to a corrupted database. 

the dhcp client should check from time to time for a new ip if the ip starts with 169 OR there should be an emergency reboot or something!

**Comment by rootzoll** [comment]
Yep a background checking process would make sense to keep track of that and trigger actions. 

Stopping and restarting LND seems like the way to go for now in case the global IP changed, because there is no manual way to add/remove IPs while running.

Adding to my version 1.0 list.

**Comment by rootzoll** [comment]
OK this is now part of the new background service - will be part of next sd card release
was not able to test it - but reboot is triggered after max 5min when local IP starts with 169.x.x.x

**Comment by phenomeus** [comment]
@rootzoll (maybe there is no notification because of closed ticket)

can we please try to differentiate between eth0 + wlan0 but also **v**ethxxxx

on my rpi4 I have docker and other stuff running and the virtual eth gets checked and the reboot triggered. I would suggest that the DHCP only checks eth0 or/ and wifi wlan0

**Comment by phenomeus** [comment]
please see #1337
