### ISSUE TITLE
Service: Add Lightning Pool

### ISSUE THREAD

**Issue by joernroeder** [raspiblitz/raspiblitz#1740]
Read More on lightning pool https://lightning.engineering/posts/2020-11-02-pool-deep-dive/ and https://github.com/lightninglabs/lightning-terminal

**Comment by ghost** [comment]
There is already this PR https://github.com/rootzoll/raspiblitz/pull/1739 :tada: :clap: for Pool

**Comment by openoms** [comment]
Started to collect some Pool usage notes I found useful: https://openoms.gitbook.io/lightning-node-management/pool

Let us know your experiences!

**Comment by rootzoll** [comment]
Merged the PRs ... now needs testing with install, deinstall & recovery.

**Comment by rootzoll** [comment]
OK tested recovery on update process - ran thru OK. Also install & deinstall over SSH menus is working.
So this will be part of v1.6.2 release - closing issue.

**Comment by ghost** [comment]
I am happy about the pool, but will there be Terminal as well? I went through code of referenced PR and it seems that it is for pool only.

I have read that Terminal has some UI for the pool. If it is the case, I believe it would be super handy to have this tool available in Raspiblitz.

Thank you ;)

**Comment by glowacki-dev** [comment]
@petrhejna It seems like LiT only added pool daemon for now and doesn't have any UI available yet.

I've actually tried adding LiT to raspiblitz some time ago, but abandoned the idea after finding out that it doesn't allow using existing daemons for loop and faraday (and now for pool as well) but will always start them on it's own. Since raspiblitz allows you to run those daemons separately there could be some issues when LiT runs them again (probably some conflicting ports or separate databases and configs leading to different behaviors depending on which daemon is used). However, their documentation [mentions](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#additional-configuration) that ability to use existing daemons will be available in the future, and it should make integration much easier.

Regardless, if you want to try LiT on your raspiblitz it's quite easy to start manually and seems to work as expected, but I'm still not sure about any possible side effects. As admin you can execute:
```
sudo ufw allow 8443 comment "LiT web UI" && \
curl -L https://github.com/lightninglabs/lightning-terminal/releases/download/v0.3.0-alpha/lightning-terminal-linux-armv7-v0.3.0-alpha.tar.gz | tar xvz && \
./lightning-terminal-linux-armv7-v0.3.0-alpha/litd --uipassword=SET_UI_PASSWORD_HERE --lnd-mode=remote --httpslisten=0.0.0.0:8443
```
and have LiT run on port 8443 (⚠️ open to the world - this may be insecure)

**Comment by rootzoll** [comment]
> I am happy about the pool, but will there be Terminal as well? I went through code of referenced PR and it seems that it is for pool only.

Yes sorry. This issue just ads pool as a CLI. Mostly because of the findings written by @glowacki-dev - will edit issue topic

**Comment by openoms** [comment]
here are some notes about pool:
https://openoms.gitbook.io/lightning-node-management/pool

The script linked contains the latest Pool version and now has an update option.

The update process:
```
# remove the old script
rm bonus.pool.sh
# download
wget https://raw.githubusercontent.com/openoms/raspiblitz/pool/home.admin/config.scripts/bonus.pool.sh
# inspect the script
cat bonus.pool.sh
# install
bash bonus.pool.sh update
```
