### ISSUE TITLE
Error message on display: "cannot create temp file for here-document: No space left on device"

### ISSUE THREAD

**Issue by rene78** [raspiblitz/raspiblitz#1806]
I am getting the error message below on my display.
![Unbenannt](https://user-images.githubusercontent.com/36115705/100343050-2763da80-2fdf-11eb-92f5-a363d13735ec.png)
The SSD is only 44% full. Or could it be the SD card? I had this in the past and a restart of the Raspiblitz helped. But it now came back after around 2 months.

**Comment by rootzoll** [comment]
Hi ... this should be fixed by updating the RaspiBlitz. There is already a v1.6.2RC2 out with a final release coming soon.
https://github.com/rootzoll/raspiblitz/issues/1785

Just power down the device and power it up with a fresh sd card image. It will go thru recovery and after that this should be fixed.

**Comment by rene78** [comment]
Hi Christian, gonna do it ASAP. Thanks a lot. Gonna close the issue again.
