### ISSUE TITLE
distinguish os

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#193]
regarding: https://github.com/rootzoll/raspiblitz/blob/adb1ff09e2caf3c000f191210a8a5f1e37f4e8b2/home.admin/97addMobileWalletZap.sh#L51

to distinguish the os, you can switch on env `$OSTYPE` and maybe use `uname` as a fallback (never used a macos).

source: https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script

**Comment by geco91** [comment]
maybe this gets solved by using the LCD for QR code display - see PR
https://github.com/rootzoll/raspiblitz/pull/334
recommend for version 1.1 milestone

**Comment by nyxnor** [comment]
Rootzoll, Im going to issues since the beggining, try to clean them all. If I have close permissions, it wont ping every time.
This is outdated about the qr code, since no lndconnect is being refactored and the web UI. Can close this.

**Comment by rootzoll** [comment]
@nyxnor Thanks for the ping ... I close this now.

How can I give just "Close Permission in Issues" on github? I only see that I can make somebody (like openoms) a "collaborator" but that would give even rights to manage the code (commit, merge PRs, etc) - what would be a bit much:

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account 

I think "an organization" has Triage as access level ... but that would mean i would need to transfer the user account repo to an organizations account.

https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization

We cant do this right now because of time ... but its someting for the v1.7.1 we could do. I opened an issue about that: https://github.com/rootzoll/raspiblitz/issues/2184
