### ISSUE TITLE
Toggling Channels Autopilot on/off triggers a Reboot of the Raspiblitz

### ISSUE THREAD

**Issue by we-do-it-lu** [raspiblitz/raspiblitz#1953]
Not a big deal but it is very surprising and quite confusing for newbies and takes time to reboot which is not optimum in meetups/demos.

**Comment by rootzoll** [comment]
when changed ... also combine with #1968 notice on switch on

**Comment by vv01f** [comment]
when at it, the option is not referenced correctly if I understand this one: https://github.com/rootzoll/raspiblitz/blob/fc1d44104bc22d85ebebd7b0d6ee2240722a9edf/home.admin/BBfundWallet.sh#L78
it's in Settings/Channel Autopilot instead

**Comment by rootzoll** [comment]
For RaspiBlitz v1.11.1  will emove autopilot & keysend options in SSH settings because it can be done thru editing the lnd.conf with SSHMENU > SYSTEM > LNDCONF .. which will then only offer to restart LND

Use `accept-keysend=1` under `[Application Options]` in lnd.conf to activate keysend

Add the following to lnd.conf to activate Autopilot:
```
[autopilot]
autopilot.active=1
autopilot.allocation=0.6
autopilot.maxchannels=5
```

Because those changes are in the lnd.conf they will persist RaspiBlitz update/recovery.

**Comment by rootzoll** [comment]
PR #4605 open .. to be part of v1.11.1rc1
