### ISSUE TITLE
Let's Encrypt for my own domain?

### ISSUE THREAD

**Issue by xpsx** [raspiblitz/raspiblitz#1977]
hello,
I want to be able to setup let's encrypt for my own domain, that I have already pointed to my public IP address. (clear net node)
of course I couldn't add my own domain as stand-alone, so I've added it as dynamicdns.

**Comment by rootzoll** [comment]
The build in LetsEnctypt `acme.sh` script in RaspiBlitz uses DNS verfication to get a valid cert on a given domain.
https://github.com/acmesh-official/acme.sh

For this a bit different that normal verfication thru serving a file on port 80 because that port is not to be made public on the RaspiBlitz. The DNS verification is not supported by all domain hosters .. so there is no easy way at the moment to make it work with your own domain.

Can you see your domain provider in the supported list of `acme.sh`?
https://github.com/acmesh-official/acme.sh/wiki/dnsapi

Maybe you could make it work with "DNS-alias-mode"?
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

**Comment by nyxnor** [comment]
@xpsx Did the info above solve for you? Please close this issue if yes.
