### ISSUE TITLE
rm: cannot remove 'error.tmp': No such file or directory

### ISSUE THREAD

**Issue by crystal-way** [raspiblitz/raspiblitz#1982]
Hello,

After a powerfailure node is still syncing, but looks like it is stuck at 99,96 and 99,97%:
Time to time, on the bottom line i see this error: "rm: cannot remove 'error.tmp': No such file or directory". Yesterday (before powerfailure) there was no this error and i believe it is to long stuck at these percents and they are not changing at all. Tried to reboot it, but did not helped. 

Node is Syncing (48) ───────────┐
                                      │  Blockchain Progress :  99.96 %         │  
                                      │  Lightning Progress  :  99.97 %         │  
                                      │  Please wait - this can take some time  │  
                                      │  Use CTRL+c to EXIT to Terminal   

 rm: cannot remove 'error.tmp': No such file or directory

**Comment by crystal-way** [comment]
Update: 

Node is Syncing (0) ───────────┐
                                      │  Blockchain Progress :  99.95 %         │  
                                      │  Lightning Progress  :  99.97 %         │  
                                      │  Please wait - this can take some time  │  
                                      │  Use CTRL+c to EXIT to Terminal

**Comment by nyxnor** [comment]
rm: cannot remove 'error.tmp' also appears to me when there is a power failure, it will disappear eventually.
Type the command `debug` on the terminal to understand about the sync progress and post it here using the link that will be genereated following the instructions on the bottom of the debug log.

**Comment by crystal-way** [comment]
Well in my case i see that percentage of the blockchain is going down. It mean's my node is not syncing.
https://termbin.com/1vav

**Comment by nyxnor** [comment]
You are in the version 1.6.2, this problem was happening that could not connect to other peers.
`2021-01-27T19:59:43Z Potential stale tip detected, will try using extra outbound peer (last tip update: 21321 seconds ago)`

It was fixed on version 1.6.3, so... update.
https://github.com/rootzoll/raspiblitz#downloading-the-software

**Comment by Omicron59** [comment]
i have this problem is lightning progress is blocked, i just saw an error in debug, how i can fix it
![image](https://user-images.githubusercontent.com/46853496/106385884-bec81e00-63d2-11eb-9600-6b7aad726046.png)

**Comment by nyxnor** [comment]
@mamar59 Have you unlocked your wallet?
![image](https://user-images.githubusercontent.com/69700936/106386389-836a2700-63b3-11eb-8d83-9ba56dec2997.png)

`lncli unlock` to unlock the wallet.
`sudo systemctl restart litd` to restart. 

Also it can be that it isn´t connection to any remote v3 addresses due to attacks on the tor network.
Seems like you´ve installed the Lightning Terminal, I haven´t tried that yet to give precise informations. Openoms referenced to you this issue cause you didn´t show this logs. If this doesnt works, I would suggest to get back on that issue https://github.com/rootzoll/raspiblitz/issues/1993

**Comment by Omicron59** [comment]
normally I have the autounlock, is there with this command "lncli unlock " does not work

[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by nyxnor** [comment]
> normally I have the autounlock, is there with this command "lncli unlock " does not work
> 
> [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

I will restart and try again, to see what happens, wait;

**Comment by Omicron59** [comment]
I think my problem comes from loopd how to uninstall it

**Comment by nyxnor** [comment]
I didnt have loop before installing the new lightning terminal, so im not sure.
To uninstall loop:
Menu > Services > Uncheck Loop

**Comment by Omicron59** [comment]
> I didnt have loop before installing the new lightning terminal, so im not sure.
> To uninstall loop:
> Menu > Services > Uncheck Loop


I have uninstalled loop and reboot is this is my node is online now, Obrigado for your help

**Comment by nyxnor** [comment]
@crystal-way Can you close this issue? All good?

**Comment by nyxnor** [comment]
This happened to me with 1.6.3 but not with 1.7.0
@rootzoll Please close this
