### ISSUE TITLE
RaspiBlitz v1.7 final Release

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2167]
- [x] create v1.7 branch
- [x] set v1.7 on sd card 
- [x] update latest code on sd card
- [x] make a final v1.7 release image & upload
- [x] sign & update md5 of image
- [x] update/merge latest doc into `v1.7` & `dev`
- [x] make last install process check from `v1.7` branch
- [x] set `v1.7` as new default
- [x] set `v1.7` tag & release on repo
- [x] send out information on twitter

**Comment by P8GRP** [comment]
Congrats! Thanks more importantly! Loading it on my second Virgin node now.

**Comment by P8GRP** [comment]
Started new RaspiBlitz load after scrubbing 1.6.3 image that was on it. Flashed 1.7 onto the micro sd. The bootup appears to be stalled at 
![PXL_20210426_203048323~2](https://user-images.githubusercontent.com/82245568/116147985-5ecdd480-a6ae-11eb-9933-6ccc7e9d2da0.jpg)

**Comment by P8GRP** [comment]
I rebooted the start up however it comes back to this point and fails and repeats. Any assistance is appreciated.

**Comment by openoms** [comment]
@P8GRP  Reflash the SDcard with the verified image. Ideally use a new, quality card.

**Comment by P8GRP** [comment]
Reflashed a new SDcard. Same issue. I cannot resolve this? installing bash completion for bitcoin-cli and lncli--2021-04-28 20:44:10--  https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/bitcoin-cli.bash-completionResolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... failed: Connection timed out.Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... failed: Connection timed out.On Mon, Apr 26, 2021, 5:53 PM openoms ***@***.***> wrote:@P8GRP Reflash the SDcard with the verified image. Ideally use a new, quality card.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
