### ISSUE TITLE
Integrate Specter Desktop in new Connect menu

### ISSUE THREAD

**Issue by dennisreimann** [raspiblitz/raspiblitz#2173]
Having a guide about [how to connect Specter Desktop with the RaspiBlitz](https://d11n.net/connect-specter-desktor-with-raspiblitz.html#on-the-raspiblitz) is good – obsoleting it with software would be even better. 

As the RaspiBlitz v1.7.0 will feature a new Connect menu, it would be good to integrate Specter Desktop there: The user can opt-in for making the bitcoind RPC available on the local network and a script could preconfigure the settings and firewall according to the guide. It could then restart bitcoind and show the user a confirmation and information on how to configure the connection in Specter Desktop.

**Comment by openoms** [comment]
Good news, you can try this in the dev branch already: https://github.com/rootzoll/raspiblitz/pull/2119

**Comment by openoms** [comment]
![image](https://user-images.githubusercontent.com/43343391/114442077-0eda1280-9bc4-11eb-8d39-45b6a07e419b.png)
![image](https://user-images.githubusercontent.com/43343391/114442124-1e595b80-9bc4-11eb-8e3c-7f9649cd78c7.png)
As testing now the workflow can be improved a it exits in the main menu after activatiing, but here is the option to show the details:
![image](https://user-images.githubusercontent.com/43343391/114442334-582a6200-9bc4-11eb-85dd-be125ec28eb7.png)
```
192.168.3.161
RPC username:
raspibolt

RPC password:
REDACTED

Host on the local network (make sure to connect from the same network):
192.168.3.161

Port:
8332

More documentation at:
https://github.com/openoms/joininbox/blob/master/prepare_remote_node.md
```

**Comment by dennisreimann** [comment]
Awesome, so this will be part of v1.7? Then I can update the article and point to that feature instead. Great work! 💪

**Comment by nyxnor** [comment]
@openoms you are so fast, thanks for the great work.

**Comment by rootzoll** [comment]
Hmm OK .. I fixed some small problem with the port ... but on my tests for v1.7 it does not look as the connection with Specter Desktop App is sucessfull - it says Tast passed above, but has a 500 error in the report and does not show further chackmarks ... see:

![Bildschirmfoto 2021-04-18 um 18 42 13](https://user-images.githubusercontent.com/2472225/115153497-88677a00-a076-11eb-877a-4c5755a7bc5c.png)

I will have the script in v1.7 (because its a generic RPC connection dialog anyway) but push this to v1.7.1 ... for finalization. @openoms if you have a quick fix for final v1.7 I am happy to add.

**Comment by rootzoll** [comment]
OK .. the raspiBlitz needed a reboot, then the connection was working with all checkmarks. Maybe this was due to the activation of the bitcoin wallet. So lets finalize this in v1.7.1

**Comment by rootzoll** [comment]
![Bildschirmfoto 2021-10-10 um 12 26 36](https://user-images.githubusercontent.com/2472225/136691820-db961220-980c-4e28-bda7-0037c2149691.png)
All checkmarks green - closing issue for v1.71. release.
