### ISSUE TITLE
SD-CARD: Non-Interactive Setup Process

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2242]
In preperation for v1.8 the v1.7.1 will contain a refactoring of a non-interactive setup process #1126 that does not require any changes to the sd card. Check for v1.8 release if any changes needed in the sd card build to optimize that further.

**Comment by nyxnor** [comment]
Is there a discussion for me to read about the build_sdcard.sh? Because I think many things dont need to be there (I will list more lines later), for example, https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L933
What if the user wants c-lightning and not lnd? Yes, it is just the gpg, but still. I think this should be a blitz.lnd.sh (unifying it with lnd.update.sh as the option inside).


Edit: **Non essential for the minimal access**
* [Parameters](https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L33) and the ifs statements of it later on (like [this](https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L598) one)
* [Bitcoin](https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L826) and [Ln](https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L933) gpgs. This [bitcoin user](https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L566)

**Comment by rootzoll** [comment]
In the beginning it was the idea that the sd card build will not call other scripts - so thats its easier to code check. But the build script got so advanced now that it makes sense to push some parts into scripts just even to prevent code duplication - especially now that we allow more config options on sd card build.

So next release where this is possible is the v1.8.

**Comment by nyxnor** [comment]
Ok, maybe even Tor and all extras that does not interfere with the system should be removed from the build.
After flashing the sd card, the first step to activate the other process should be through ssh or webui and toggling it to `on`. Also, the parameters of the build script should also be moved after the user can access the blitz interface, because if someone flashes your image, they are set to your parameters, and the way it is done, he wont be optimized unless he builds the image, but with a reduced image config, all parameters being set after. This will reduce drastically the dependency on the build and just the scripts called after. It is good that the build dont call any other scripts. Using this options, the updates will just get the new scripts, set permissions, and some things more.

Oh, but what about building from your [forked repo](https://github.com/rootzoll/raspiblitz/blob/2a89fae133bcf4e0a4b66557750ebdf0902f7f39/build_sdcard.sh#L53)? 
It still will be available, the minimal blitz will give access to the webui and then the user can choose there, with an option of using the default values of the main project repo and other configs.

Edit: Correcting myself
Maybe Tor is more difficult to retrieve from the build because the whole aspect and changes Ive done to the build:
* uses Tor v3 onion address for the source (I think this could be default, cause it aint gonna take much time as it is just for the Tor pkgs, but reaching normal updates will take a little bit longer)
* let the user input bridges before Tor starting, and how is he going to access just the WebUI on Tor browser if his Tor cant start without bridges? The good old ssh or WebUI through clearnet will have to be used.

### The process I imagine:
#### First use
1. Flash the sd card
1. Add bridges through ssh if necessary
1. Access the WebUI on the Tor Browser
1. Configure the parameters from now on, Bitcoin, Lnd, C-Lightning, Github forked repo, Tweak boot drive or for simplicity use default values
#### Updates
1. Access the WebUI on the Tor Browser
1. Clone defined repo and maybe an script to set permissions correctly if something is wrong
1. Use previous defined values for the services
1. Test this multiple times....
#### Correction of unsolved errors
1. Will need to flash

**Comment by rootzoll** [comment]
I nice way to add network configurations to a sd card build is also to write a file to the sd card when connected to your laptop .. like its done for the WIFI config.

But basically if the RaspiBlitz can detect itself that it needs additional Tor config - it could be done also on the WebUI start page that you call with your normal browser locally. There it tells you to install Tor Browser and and yould also tell you that more Tor config is needed, etc.

**Comment by rootzoll** [comment]
I think we had the major refactors of the build script already fixed. @nyxnor I would close this issue but if you see ideas in here that are not reflected by other open issue please create a new one.
