### ISSUE TITLE
RaspiBlitz v1.7.0-> .onion-address missing

### ISSUE THREAD

**Issue by silvester235** [raspiblitz/raspiblitz#2280]
I recently updated to RaspiBlitz v1.7.0.

Before v1.7.0 the "Raspiblitz Status Screen" showed the .onion-address
However under v1.7.0 this is not displayed anymore. Where can I find the .onion-address?
<img width="441" alt="Screen Shot 2021-05-05 at 19 57 23" src="https://user-images.githubusercontent.com/79768798/117144719-76a70600-addc-11eb-8432-4bd9493e51c7.png">

**Comment by openoms** [comment]
`bitcoin-cli getnetworkinfo`

**Comment by silvester235** [comment]
@openoms thanks!

**Comment by rootzoll** [comment]
Just for background: Because the short Torv2 addresses are deprecated and now the longer Torv3 addresses are used by bitcoin core the bitcoin onion-address got too long to display on the LCD and I replaced it on the display with the block number information. But of course as openoms pointed out you can find that information still by calling bitcoin-cli directly.
