### ISSUE TITLE
files deleted without warning

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#234]
https://github.com/rootzoll/raspiblitz/blob/ed748e433ff3548da05530d97756143e5b4f5991/home.admin/XXupdateScripts.sh#L33

This should not be done - removing all shell scripts in a directory without warning the user.
I had additional scripts for other things running on my node that got deleted.

**Comment by rootzoll** [comment]
Ouch OK. Maybe the delete should be a "--clear" option on the script.

The XXupdateScripts is not the recommended for "Update" anyway ... maybe I need to change/rename that script anyway. Its more for syncing with your GitHub during development.

Regular system updates should always be by replacing the complete SD card. Own scripts would need to be placed on the HDD and need some manual reactivation/install after an update.

**Comment by fluidvoice** [comment]
redoing the SD card seems overkill to me, unless it's really necessary. One thing I wondered about, which needs upfront documentation visibility, is which upgrade method to choose and that is ensured not to delete the already synced blockchain DB.  In my case running XXupdateScripts and rebooting worked quite well after I fixed one problem with it (which I opened an issue on).

**Comment by rootzoll** [comment]
Sidenote: I renamed now XXupdateScripts.sh to XXsyncScripts.sh ... because it should be clear that this is a dev tool - not a way to to update. I think some issues people having here are a result just updating with that script to avoid the sd card update. Why the sd card update is improtant I did wrote here: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#why-do-i-need-to-re-burn-my-sd-card-for-an-update-after-version-098

ABOUT deletion of files without warining: 
the script now needs a explicit "-clean" 

I will close this issue for now.
