### ISSUE TITLE
lightning addresses

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#2408]
Regarding this C-lightning pull https://github.com/rootzoll/raspiblitz/pull/2352 for @openoms 
Ok, is being added the possibility to run parallel chains with mainnet, testnet and signet.
But how can I determine which ones are active?
Yes, I can source `source <(/home/admin/config.scripts/network.aliases.sh getvars <lnd|cln> <mainnet|testnet|signet>)` 3 times for each implementation, meaning 6 times, but that is not smart. Is it set in the `raspiblitz.conf`?

```bash
check=$(echo "${CHOICES}" | grep -c "y")
if [ ${check} -eq 1 ]; then
  echo "LND setting CHANGED .."
  #lncli getinfo | jq -r '.uris [0]'
  # https://github.com/rootzoll/raspiblitz/pull/2352#issuecomment-867729234
  source <(/home/admin/config.scripts/network.aliases.sh getvars lnd mainnet)
  ln_getInfo=$($lncli_alias getinfo 2>/dev/null)
  ln_external=$(echo "${ln_getInfo}" | jq -r '.uris' | grep onion | cut -d'"' -f2 | cut -d':' -f1)
else
  echo "LND setting unchanged."
fi

check=$(echo "${CHOICES}" | grep -c "z")
if [ ${check} -eq 1 ]; then
  echo "C-Lightning setting CHANGED .."
  # https://github.com/rootzoll/raspiblitz/pull/2352#issuecomment-867700419
  source <(/home/admin/config.scripts/network.aliases.sh getvars cln mainnet)
  cln_external=$(echo "$lightningcli_alias getinfo" | grep ".onion" | cut -d= -f2)
else
  echo "C-Lightning setting unchanged."
fi
```

**Comment by openoms** [comment]
yes, raspiblitz conf will show all the active ones with the naming:
`testnet`
`mainnet`
`signet`
`lnd`
`tlnd`
`cln`
`tcln`
`scln=on`

both the implementation: lnd or cln and the chain: testnet, mainnet, signet will fall back to the default unless otherwise specified when calling the scripts.
This basically governed by sourcing the network.aliases.sh.

To start off planning to be able to set defaults as:
`chain=main` or `test`
and
`LNdefault=lnd` or `cln`
in the `raspiblitz.conf`
