### ISSUE TITLE
Strange behavior with pihole

### ISSUE THREAD

**Issue by hcarrega** [raspiblitz/raspiblitz#247]
Every time I reboot can’t get pihole working again with RaspiBlitz maybe some configure delete something

**Comment by rootzoll** [comment]
I dont know about pihole before, it is this project, correct? https://pi-hole.net

What is the benefit running it with RaspiBlitz/LightningNode?

**Comment by hcarrega** [comment]
I’m using only to block ads on my home network

**Comment by rootzoll** [comment]
I cannot see where it would should conflict - maybe something with systemd? I can just guess here, sorry. 

Because this not a directly lightning/RaspiBlitz related service - I am closing the issue. But if pihole starts to send mircopayments as compensation to the websites where it blocks ads, let us know :)
