### ISSUE TITLE
FEATURE REQUEST: Initial sync choice TESTNET vs MAINNET

### ISSUE THREAD

**Issue by we-do-it-lu** [raspiblitz/raspiblitz#2508]
When someone installs Raspiblitz for the first time the time required by the download of the complete MAINNET is an unnecessary barrier all he wants is play with his Blitz ASAP, would be great to have the option "sync TESTNET" vs "sync MAINNET" at first start.

**Comment by rootzoll** [comment]
Because with the recent refactoring of the setup options for the v1.7.1 we decided to not have the "TESTNET" as an option from the beginning and offer Testnet & Signet as an option you can run in parallel once MAINNET is running.

I know that makes it not easy&fast to setup .. but making sure that the whole setup process is working now with also c-lightning coming as an option with v1.7.1 would double all the testing efforts. Keep in mind that also with v1.8 we plan to introduce another optional setup process with the WebUI next to the SSH - so first we need to get that stable.

Once the new setup processes are implemented and well tested we might take a look how to provide a quick testnet setup without mainnet .. but I will push this up to v1.8.1 to take another look.

**Comment by we-do-it-lu** [comment]
Thank you @rootzoll, makes sense.

**Comment by rootzoll** [comment]
PR #4579 allows developers to internally switch bitcoind to testnet (to simulate mainnet) during SSH setup (when no former blockchain is found after setup).

This is for now just for bitcoin and is excepted to cause trouble when adding LND or CLN - but its a start into that direction (#4580 will pick up then in later version).
