### ISSUE TITLE
Backup HDD

### ISSUE THREAD

**Issue by wuestenigel** [raspiblitz/raspiblitz#256]
Hey,

is there a way to backup my HDD?

As a user I want to backup my personal settings, but also the blockchain data so save some time in case of a HDD crash.

Already tried to plug it into my iMac, but it wasn't readable. Is there any existing script on the raspiblitz image that may help?

**Comment by fluidvoice** [comment]
admin@node $ `man rsync`
or google about how to run **rsync**.

**Comment by fluidvoice** [comment]
Here is a decent page I found. Has everything except how to run over SSH (need to find this still):
https://www.thegeekstuff.com/2011/01/rsync-exclude-files-and-folders/

**Comment by wuestenigel** [comment]
Thank you

**Comment by fluidvoice** [comment]
> Thank you

Well I needed to figure this out for myself so I can make backups. Here is my first stab at it.  Let me know if you try it - if it works or you have problems...

//////// assuming you are using Linux machine to backup remote Raspiblitz node.
// I don't know if backing up while the Raspiblitz node is running works OK. Might slow Raspi or backup.
// So it might work better to stop things then reboot after the backups are complete
// via SSH stop services: 
`sudo systemctl stop bitcoind.service` 
`sudo systemctl stop lnd.service`
// then after backup completes via SSH run: 
`sudo reboot` to restart Raspi 

//// Notes: 
/// the prompt for the FIRST password below is your local machine's admin password (for sudo)
/// '**raspi**' below should be replaced with the **IP address** of your Raspiblitz node
/// replace '/run/media/brad/Ext3/raspiblitz/' with your desired backup destination
/// (eg. my USB HDD is mounted at '**/run/media/brad/Ext3**' and '**/raspiblitz**' is my dest dir)
/// change `-avzphn` to `-avzph` below to change (dry run) option to perform a real backup
/// dry run can be used to see how much disk space will be used.

// backup Raspiblitz root/SD-card. SECOND password prompt is for your Raspiblitz admin user
`sudo rsync --stats -avzphn --exclude="tmp" --exclude="sys" --exclude="lost+found" --exclude="mnt" --exclude="proc" --exclude="dev" --exclude="media" admin@raspi:/ /run/media/brad/Ext3/raspiblitz`

// backup Raspiblitz bitcoin+blockchain dirs. 
`sudo rsync --stats -avzphn --exclude="lost+found" --exclude="swapfile" admin@raspi:/mnt/hdd /run/media/brad/Ext3/raspiblitz/`

**Comment by fluidvoice** [comment]
`sudo rsync --stats -avzphn --exclude="tmp" --exclude="sys" --exclude="lost+found" --exclude="mnt" --exclude="proc" --exclude="dev" --exclude="media" admin@raspi:/ /run/media/brad/Ext3/raspiblitz/`

at the end it shows it takes **8.2GB** to backup the root (SD card)...

> Number of files: 146,631 (reg: 115,366, dir: 12,133, link: 19,102, special: 30)
> Number of created files: 146,630 (reg: 115,366, dir: 12,132, link: 19,102, special: 30)
> Number of deleted files: 0
> Number of regular files transferred: 115,366
> Total file size: 8.22G bytes
> Total transferred file size: **8.22G** bytes


and for the bitcoin and blockchain dirs (obviously non-dry-run will take a long time)...

`sudo rsync --stats -avzphn --exclude="lost+found" --exclude="swapfile" admin@raspi:/mnt/hdd /run/media/brad/Ext3/raspiblitz/`

**Number of files: 11,348 (reg: 11,328, dir: 20)
Number of created files: 11,348 (reg: 11,328, dir: 20)
Number of deleted files: 0
Number of regular files transferred: 11,328
Total file size: 276.23G bytes
Total transferred file size: **276.23G bytes**

**Comment by rootzoll** [comment]
@fluidvoice thanks for sharing your backup efforts. And you are correct - if you do any backup i would always recommend to stop the lightning services. But you can ignore the bitcoin data on backup - there is no personal data in there and all can be redownloaded/resynced from public networks.

To generally anwere the topic of backup (because it comes up a lot) - started an FAQ on that:
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-backup-my-lightning-node

**Comment by fluidvoice** [comment]
> @fluidvoice thanks for sharing your backup efforts. And you are correct - if you do any backup i would always recommend to stop the lightning services. But you can ignore the bitcoin data on backup - there is no personal data in there and all can be redownloaded/resynced from public networks.
> 
> To generally anwere the topic of backup (because it comes up a lot) - started an FAQ on that:
> https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-backup-my-lightning-node

EDIT: @rootzoll one thing I noticed. Rsync using the **admin** user does get some though not a lot of "access denied" errors. I think this might be because of the various users (admin, bitcoin, pi, root).  But I'm not sure. I'll have to investigate how to backup everything regardless of file ownership rights.

I think backing up the blockchain DB is much preferred to resyncing for some people, myself included, due to slow internet connection.  It took me like a week to sync my node. That's a lot of downtime if you need your node up ASAP.  Plus some people have experienced DB corruption on power failure. It's a total PITA to  have to resync when that happens.  Granted backing up takes a while too. Better if connected via ethernet.
  Even aside from the DB, when something goes wrong that you cannot figure out/fix having to re-burn the SD card is also a PITA. Even worse is if you have dev files, other scripts, or other projects also on the same node.  Backup is a must!

Something else. Backing up via SSH, esp via WiFi, while it works, is obviously slow. Direct connecting a USB HDD to the Raspi would be much better but my drive is not powered and my Raspi cannot handle two USB drives connected at the same time. Plugging it in, crashes the Raspi processes and could risk data loss. One solution is to buy a powered USB hub that can handle two or more drives.   My Raspi power supply is rated 2.5 amps. Would upping that to a 3.5 amp PS help?  I'm doubtful.  Powered hub is prob the way to go.

**Comment by wuestenigel** [comment]
Thanks for sharing the scripts you created.

I agree that bitcoin blockchain is public, but on the other hand my node should also have a high availability. If I need to download the Blockchain data again, my LN node will be offline for a week. (Question: Is there a reputation algorithm in LN for calculation routes and does a high downtime decreases this kind of reputation?)

On the other hand I'm not sure if I understood the LND backup correctly. 

1) If I do not backup the LND data, my funds may be lost in case of HDD crash?

2) Even if I make a backup it may occur that I loose my funds because of the built-in punishment system that prevents replay attacks? So If I install an old LND image from another disk I may get punished if there are newer transactions?

**Comment by fluidvoice** [comment]
1. No. See: https://github.com/rootzoll/raspiblitz/blob/783c5de56fd4b2ca263699c6d3ccacd87c4da446/README.md#recover-your-coins-from-a-failing-raspiblitz

**Comment by fluidvoice** [comment]
dropping some notes here on how to automate backing up (hourly/daily/weekly) using `rsync` and cron jobs.  Use this combined with the rsync commands I used in post https://github.com/rootzoll/raspiblitz/issues/256#issuecomment-452727180 or just use it to backup your lnd, bitcoin, home, etc. folders.

> edit your user cron file with "crontab -e" and add this line'
> 
> */30 * * * *   rsync -avu --delete /lnd_data_folder/ /pendrive_folder/
> 
> (Replace each folder with your configuration)
> 
> It will copy every 30 minutes LND folder

When you run `crontab -e` you see the cron file's default content with notes:

//# Edit this file to introduce tasks to be run by cron.
//#
//# Each task to run has to be defined through a single line
//# indicating with different fields when the task will be run
//# and what command to run for the task
//#
//# To define the time you can provide concrete values for
//# minute (m), hour (h), day of month (dom), month (mon),
//# and day of week (dow) or use '*' in these fields (for 'any').#
//# Notice that tasks will be started based on the cron's system
//# daemon's notion of time and timezones.
//#
//# Output of the crontab jobs (including errors) is sent through
//# email to the user the crontab file belongs to (unless redirected).
//#
//# For example, you can run a backup of all your user accounts
//# at 5 a.m every week with:
//# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
//#
//# **For more information see the manual pages of crontab(5) and cron(8)**
//#
//# m h  dom mon dow   command

**Comment by rootzoll** [comment]
@fluidvoice --> I explained a bit more why I choosed "update by sd card" in the FAQ now - please see here: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#why-do-i-need-to-re-burn-my-sd-card-for-an-update-after-version-098

ABOUT BACKUP:

LND just announced some backup solution is "comming soon" - at least thats how I understood that tweet from Alex: https://twitter.com/alexbosworth/status/1083394904900825089

Instead of stopping LND+rsyncing by cron and so still risking to have an old backup and loosing all funds, I would recommend to look into a RAID1-Solution to protect against HDD data loss. When the OS writes the data to two HDDs at the same time - that could be the safest way todo it. But I never setup a RAID1 with two HDD over USB on Raspberry ... but if possible, thats most def something to look into to add the raspiblitz as a feature - even if LND comes up with some other backup solution in the future. Please share if anybody has some experience in that context.
