### ISSUE TITLE
"node is syncing" screen on most of the time

### ISSUE THREAD

**Issue by thephizzz** [raspiblitz/raspiblitz#2643]
After upgrading to 1.7.1 the lcd screen stays on the 'node is syncing' screen with btc at 100.00% and lnd at 99.99% for most of the time. Occasionally it switches to the main screen but always goes back to 'syncing'.
I can still go to the terminal and execute the main menu etc.
Anyone else seeing this behavior?

**Comment by rootzoll** [comment]
The detection was changed as part of the refactor ... not seeing this on my test nodes, but maybe the sync detection needs to recalibrated.

**Comment by thephizzz** [comment]
It seems to have gotten better over the last few days. More main screen than not.

**Comment by Mars2078** [comment]
I have the same problem. Just started my first ever node and I'm almost there but it seems to be stuck... BTC at 100% but lnd after logging in shows 'syncing' and in a few seconds restarts and asks to login again. After I login same thing happens. Have I missed something in setup process?

**Comment by rootzoll** [comment]
@Mars2078 please go to terminal (CTRL+c multiple times) run `patch` & then `restart` - let us know if this fixes your problem

**Comment by Mars2078** [comment]
That worked. Very pleased to see my new Node operational. Thank you for your work

**Comment by JurGi7** [comment]
I have the same problem, after updating to 1.7.1 I often see the message "Waiting for Chain Sync". Furthermore, I see on the BTCPayserver interface for two weeks "Your Node are synching". In the meantime, however, it works and seems to be synchronous. What can I do?

![screen](https://user-images.githubusercontent.com/55794093/139798487-4464ae23-92bc-4ecb-83bc-c409ed3a5b36.png)

**Comment by openoms** [comment]
@JurGi7 check if
`sudo systemctl status nbxplorer`
and
`sudo journalctl -n10 -u nbxplorer`
has any errors.
Restart the services with:
`sudo systemctl restart nbxplorer`
`sudo systemctl restart btcpayserver`

**Comment by thephizzz** [comment]
Thank you for the reply.

Here are the results of those commands:

 

sudo systemctl status nbxplorer – service could not be found
and
sudo journalctl -n10 -u nbxplorer - -- Logs begin at Tue 2021-11-02 12:00:57 GMT, end at Tue 2021-11-02 21:21:12 GMT. --

-- No entries –

 

Both commands below give: Failed to restart xxxxxxx.service: Unit xxxxxxx.service not found.

sudo systemctl restart nbxplorer
sudo systemctl restart btcpayserver

**Comment by openoms** [comment]
@thephizzz the above command was meant for @JurGi7 as tagged.
Sorry for the confusion, @JurGi7 should open a new issue for BTCPayServer related problems. His comment (and mine) is not relevant here

**Comment by JurGi7** [comment]
Hi openoms,
thank you for your answer. 
Here are the outputs on the commands. nbxplorer and btcpay restarted.
Jurgi

first:

nbxplorer.service - NBXplorer daemon
   Loaded: loaded (/etc/systemd/system/nbxplorer.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-11-02 17:20:49 CET; 17h ago
 Main PID: 3485 (dotnet)
    Tasks: 38 (limit: 4532)
   CGroup: /system.slice/nbxplorer.service
           ├─3485 /home/btcpay/dotnet/dotnet run --no-launch-profile --no-build -c Release -p NBXplorer/NBXplorer.csproj --
           └─3988 /home/btcpay/NBXplorer/NBXplorer/bin/Release/netcoreapp3.1/NBXplorer

Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Configuration:  BTC: Height: 708006
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Explorer:       BTC: Handshaked node
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Explorer:       BTC: Current Index Progress not found, start syncing from the header's chain tip (At height: 708006)
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Explorer:       BTC: Starting scan at block 708006
Nov 03 10:49:21 raspberrypi dotnet[3485]: fail: Explorer:       BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Events:         BTC: Node state changed: NBXplorerSynching => NotStarted
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Configuration:  BTC: Testing RPC connection to http://localhost:8332/
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Configuration:  BTC: RPC connection successful
Nov 03 10:49:21 raspberrypi dotnet[3485]: info: Configuration:  BTC: Full node version detected: 220000

second:
- Logs begin at Wed 2021-11-03 06:56:06 CET, end at Wed 2021-11-03 10:51:10 CET. --
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Explorer:       BTC: Current Index Progress not found, start syncing from the header's chain tip (At height: 708006)
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Explorer:       BTC: Starting scan at block 708006
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
Nov 03 10:51:10 raspberrypi dotnet[3485]: fail: Explorer:       BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Events:         BTC: Node state changed: Ready => NotStarted
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Configuration:  BTC: Testing RPC connection to http://localhost:8332/
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Configuration:  BTC: RPC connection successful
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Configuration:  BTC: Full node version detected: 220000
Nov 03 10:51:10 raspberrypi dotnet[3485]: info: Configuration:  BTC: Loading chain from cache...

**Comment by openoms** [comment]
@JurGi7 moved the discussion about NBXplorer to  a separate issue: #2697 please continue there.
