### ISSUE TITLE
detect c-lightning wallet locked

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2691]
In the systembackgound scan thats feeding the status cache c-lightning is seen as always unlocked - this needs to be implemented for v1.8

**Comment by openoms** [comment]
Currently the locked state causes the general error `ERROR_TALKING_TO_LIGHTNINGD` and exits with error code 2:
https://github.com/ElementsProject/lightning/blob/3d8293dbf40d2d940a89850ecc87b8c6e1fa0772/cli/lightning-cli.c#L26

The log error is if the passwordfile is not present:
`Could not read pass from stdin`
https://github.com/ElementsProject/lightning/blob/3d8293dbf40d2d940a89850ecc87b8c6e1fa0772/common/hsm_encryption.c#L111

The statusscan is attempting to get the error from the journal output:
https://github.com/rootzoll/raspiblitz/blob/d81801d2a911cdfd45108d04b5f050199b57ca97/home.admin/config.scripts/blitz.statusscan.sh#L287

isn't `blitz.statusscan.sh` doing the relevant scan?

**Comment by maximlomans** [comment]
ich bekomme genau den gleichen fehler

still at 98% sync
autounlock is enabled
can i edit c-lightning/config to point towards 9735 instead of 9736 or is it supposed to be that way,  ..in a node with both it and lnd.

\# lightningd configuration for bitcoin mainnet

network=bitcoin
announce-addr=127.0.0.1:9736
log-file=cl.log
log-level=info
plugin-dir=/home/bitcoin/cl-plugins-enabled

 \# Tor settings
proxy=127.0.0.1:9050
bind-addr=127.0.0.1:9736
addr=statictor:127.0.0.1:9051/torport=9736
always-use-proxy=true
 
i guess only one of them runs at any one time anyways, so technically i could but that means i'd have to edit all port entries in .lightning/config
and add ufw 9736/tcp allow entry, there isn't one.

i couldn't say it got temp 'fixed' by enabling LND instead.
but still occasionally getting statuscheck error code 124

**Comment by openoms** [comment]
@maximlomans please open a new issue for this as you question is not related here.
(you can't run LND and c-lightning on the same port,  but can edit the c-lightning port to.9735 if LND is deactivated )

**Comment by openoms** [comment]
added the detection from logs, but keeping the v1.8 milestone as in the next c-lightning release will be able to support to specific exit code introduced in https://github.com/ElementsProject/lightning/pull/4908

**Comment by rootzoll** [comment]
Worked on my testing machine ... closing issue for v1.8.0 release.
