### ISSUE TITLE
retest: getting c-lightning seedwords on wallet creation

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2766]
when a fresh blitz is setup with lnd, retest that you get also fresh seed words on installing c-lightning from settings menu in parralell.

**Comment by openoms** [comment]
This is a bit tricky because CL autogenerates an hsm_secret (onchain wallet) when it is started and there is none present.
Need to be careful to delete any existing wallet which was accidentally created without seedwords.

A solution would be to avoid starting CL if there is no wallet yet.
The `cl.check.sh prestart` script started in the systemd service could take care of it.

**Comment by rootzoll** [comment]
`prestart` could be a good place to check/create wallet.

**Comment by openoms** [comment]
the prestart is limited to the `bitcoin` user so went to add it to the cl.install.sh so the wallet is created from seed before CL is first started, see #2822

**Comment by openoms** [comment]
if c-lightning is chosen during the initial setup the wallet with seedwords does overwrite the autogenerated wallet already:
https://github.com/rootzoll/raspiblitz/blob/6cd17ad27a901cc852fc734bd23500c02df02d57/home.admin/_provision.setup.sh#L388

**Comment by rootzoll** [comment]
@openoms you reopened this issue .. anything still to consider for final v1.7.2 release on this?

**Comment by openoms** [comment]
This has been tested extensively during the backup-recovery changes. Can close again.
