### ISSUE TITLE
ssh keys backup refactor

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2820]
see #2818 & # #2819 - merged for final testing

TODO: create a v1.7.1 Blitz - then insert a RC1 sd card and check if same SSHd key (no changes keys warning) and backup and conversion worked correctly (already before starting setup)

**Comment by openoms** [comment]
[v1.7.2RC1] having an issue with the ssh connection during a failed setup:
if the disk fails to mount (due to hardware issues) the raspiblitz restarts automatically and the ssh service fails to start afterwards.

Also happens after a restart to apply the uasp-fix
![1f9285c7-5a95-4743-b09a-0a808a0e8b22](https://user-images.githubusercontent.com/43343391/146679094-a481ee57-95ec-413b-90ec-f44e3f92b6b9.jpg)

**Comment by openoms** [comment]
thanks, the above is fixed in e66848a

**Comment by openoms** [comment]
Had a tough time on Ambian (Odroid HC2) after recovering my old disk:
```
Permission denied (publickey).
```

It did not get solved when placed the `ssh.reset` file in the `/boot/` dir on the sdcard.

The only way to get in was to create a file on the SDcard at `/home/admin/.ssh/authorized.keys` and paste my laptop's ssh pubkey to it. 
It was still asking for password A so there are some quite tough default values on the ssh server.
Would like to find out how to improve this, but until then this is a note for other Armbian users.

The issue was this line on the end of the `sshd_config`:
```
AuthenticationMethods publickey,keyboard-interactive
```
which is pubkey + password.

It should be instead (at least initially):
```
AuthenticationMethods publickey
AuthenticationMethods keyboard-interactive
```
which is to ask for password if there is no authorized pubkey avaliable.

**Comment by rootzoll** [comment]
@openoms If I check on the sdcard image rc1d with bullseye the `/etc/ssh/sshd_config` there is no entry for `AuthenticationMethod`

Should we set it explicitly? Or what are the measures to take here?

At least where this can go differently is on `recovery` from older distros when with `sudo rm -rf /etc/ssh/*` the whole default bullseye config gets deletetd and the old config from SSD gets copyied over ... so maybe the problem can be find here?

https://github.com/rootzoll/raspiblitz/blob/8e3c9774a239ba54befc7bef7410d77e49de0290/home.admin/config.scripts/blitz.ssh.sh#L152

**Comment by rootzoll** [comment]
@openoms this is one of the last things to address before building a new RC - whats the best direction here from your perspective?

**Comment by openoms** [comment]
I think the problem is that if key-auth only was set the setting file is restored, but the `.ssh/authorized_keys` directory is not.

Should use `cp -ra` instead of just `cp -a` in the backup and restore function.

**Comment by rootzoll** [comment]
OK havent seen anymore problems on this. Closing issue for release.
