### ISSUE TITLE
Used the Update funciton on 1.7.1 and unable to launch raspiblitz 

### ISSUE THREAD

**Issue by mantiev** [raspiblitz/raspiblitz#3205]
I get the below error

Starting SSH user interface ... (please wait)
/home/admin/_cache.sh: line 198: redis-cli: command not found
/home/admin/_cache.sh: line 198: redis-cli: command not found
setupPhase(done) state()
FAIL: /home/admin/raspiblitz.info does not exist or missing state.
Check logs & bootstrap.service for errors and report to devs.

It looks like it wiped out some needed info.

Appreciate any assistance.

Thanks.

**Comment by mantiev** [comment]
I have looked at the errors and matched them with the correct file and everything looks correct.  I tried to upgrade to 1.7.2 and it didn't recognize my admin password.  At this point my node is completely down.

**Comment by maximlomans** [comment]
post your logs 

if anyone comes along they can atleast get an idea of what the issue might be, without having to start a back and forth.

have you tried the deafult one ? raspiblitz  
the admin password is the first pass you're asked to set,  when doing a recovery anyways, if i remember correctly, ..it's only been an hour since i walked that path.

now it seems like a case of the blind leading the blind, oops.
 
 - luckily i closed all channels before hand and i could continue with a fresh install 

my debug -lnd crashed 
- but my issue was not the password 
- i didnt bother with checking the logs,
-  shutdown, format & write
i had upgraded my other day node the previous day so i thought i spare myself the trouble and have it done in 30min.

 

have you tried to set a new admin login through raspi-config ?

**Comment by mantiev** [comment]
Thanks for the reminder.  That allowed me to login and setup the node.  I'm back up and running.  Thank you again.

**Comment by mantiev** [comment]
Issue resolved with upgrading.

**Comment by souladventurer** [comment]
Hey @mantiev, I'm having the same issue and Im a bit of a dummy. My password seems to work but Im stuck in the loop of getting the same message every time I try and log in. How did you resolve?
