### ISSUE TITLE
WebUI Balance is too low

### ISSUE THREAD

**Issue by Yonben** [raspiblitz/raspiblitz#3308]
Hi,

Just wanted to inform, I've been getting validation errors on "sending" fromthe WebUI telling me my balance is too low to send funds when it's not (and I can still submit and it works).

Willing to work on fixing it, just wanted to at least document the bug first :)

**Comment by rootzoll** [comment]
@fusion44 can you point into the right direction to get this fixed?

**Comment by Yonben** [comment]
Similarly:
![image](https://user-images.githubusercontent.com/7793347/187745041-b97b8be4-6fe5-4d69-97ff-701576aadc13.png)
It seems I don't use 97% CPU. Is it something I'm not reading properly in `top` or a display error in the webui?

@fusion44 I'd love some direction on how to work on the webui to try and tackling these myself :)

Weird timing on the first pic, but anyway here goes again
![image](https://user-images.githubusercontent.com/7793347/187746031-1cbf1fed-fbd6-4a7a-b9d7-31500cf31e7d.png)

It seems it just takes the CPU value when loading the page and not refreshing it. Not sure if by design, just confusing I guess :/

**Comment by cstenglein** [comment]
Hi @Yonben 

The first bug is related to https://github.com/cstenglein/raspiblitz-web/issues/401 - sorry for not documenting much. If you want I can write more information in the issues if you Like information on specific issues.

Regarding the CPU: It's calculated from the load. See the formula the WebUI uses here: https://github.com/cstenglein/raspiblitz-web/blob/master/src/pages/Home/HardwareCard.tsx#L29

Here is an article which explains the load averages: https://www.tecmint.com/understand-linux-load-averages-and-monitor-performance/

So that means you look at the load average, you are using **3.78** Cores out of 4 in the last minute => 94,5%, so seems right but I understand if it's confusing. Maybe we should display that differently?

**Comment by Yonben** [comment]
@cstenglein thanks for details!
I'll take a look at the repo tonight and check what i can find. I'll comment on the issue there :)

**Comment by cstenglein** [comment]
FYI @Yonben fixed that issue in https://github.com/cstenglein/raspiblitz-web/pull/449 :+1: 

Can be closed IMO
