### ISSUE TITLE
Problem with mempool space, addresses do not load

### ISSUE THREAD

**Issue by FlorianHubl** [raspiblitz/raspiblitz#3460]
Im not a techy so I need a good explanation. When I go to mempool space on my raspiblitz and click one a adress the adress do not load. After some time I get a timeout. I have electrs 0.9.9. Any ideas how to fix this?
<img width="1232" alt="Bildschirmfoto 2022-11-20 um 13 46 48" src="https://user-images.githubusercontent.com/49409175/202902755-278a68c8-f5a9-4215-a90c-4062ddf1c2c3.png">

**Comment by rootzoll** [comment]
TODO: retest with v1.8.0c image

**Comment by FlorianHubl** [comment]
Thank you. I had to do it with v1.8.0c, then install electrs 0.9.10 and then restart electrs and mempool.
cd /home/electrs/electrs
sudo -u electrs git fetch
sudo -u electrs git reset --hard v0.9.10
sudo -u electrs /home/electrs/.cargo/bin/cargo build --locked --release
(*Wait till this completes before executing the system restart*)
sudo systemctl restart electrs
sudo systemctl restart mempool

**Comment by mitohund** [comment]
I know this is closed, but since it also says "bug - unconfirmed" I thought I'd just chime in to say that I also have this issue.

**Comment by rootzoll** [comment]
I see if I can give this another check during release candidate phase

**Comment by mitohund** [comment]
Don't know if it helps, but here's what happened for me since my last message (I'm on 1.8.0c): I reinstalled electrs (keeping the index), but mempool still would not load addresses (everything else though). An hour or so later, it started loading addresses with a 1-2 minute loading time. Another day later, they seem to be loading fine. I had checked htop load averages at the time and they were fine.

The thing is, I had only updated to 1.8.0 maybe two weeks ago, and at the time I had reinstalled both mempool and electrs.

EDIT: It's still behaving weirdly. Some addresses are loading fine, some slowly, others not at all.

**Comment by rootzoll** [comment]
I was able to reproduce it shortly - with diffrent error messages (did also not seem cossitent) but now it works again on my test machines. Maybe this is electrs related - tested with eletcrs 0.9.10 which will be part of RaspiBlitz v1.9.0 release. So I will push this up - hope this gets more stable with future electrs versions. To be further monitored.

**Comment by mitohund** [comment]
I believe I read somewhere in the mempool.space docs that electrs might be a bottleneck and that fulcrum is recommended? I also read that address loading behaviour depends on the number of transactions at that address.

I think I can reproduce that. Addresses with one transaction load pretty instantly. Addresses with a few thousand transactions give an error. In between, high loading times. I'm on electrs 0.9.10 now (I think...).

**Comment by malt33k** [comment]
Running raspiblitz 1.8.0 and having the same issue. Do not have electrum rust server enabled, does this have to be a requirement? Thought setting txindex=1 would include the address information.
![Screenshot 2022-12-26 at 10 07 07 AM](https://user-images.githubusercontent.com/120649635/209562150-000f435a-2a5d-4f0d-b618-ce1c84e9fd6f.png)

**Comment by mitohund** [comment]
Since I just stumbled upon this again, here's an exemplary (totally random) address that always times out on my Raspiblitz: https://mempool.space/de/address/bc1q9s2kmdhn8xt0qjuks0faetq76ycq7zvq4jdfwf

**Comment by myxmaster** [comment]
Like @malt33k I get the same error message immediately for any address I try to look up. I installed mempool a few days ago, so index building is done for sure.

So I also want to know: Is the electrum rust server a requirement? If yes, users should get notified in case mempool is installed without electrum rust server. If no, what can I do to fix it?

**Comment by mitohund** [comment]
I believe it's required. Why don't you just try and install it?

It's true though that if it is required, there should be some kind of notification of dependencies.

**Comment by myxmaster** [comment]
Because of the weak hardware I don't want to install more than needed.

Anyway, I read more about it and it seems that, to look up addresses, electrum rust server as backend is needed.
-> When a user triggers mempool installation, it should be checked if electrum rust server is installed already, if not it should inform about the limited functionality and offer to install electrum rust server first.

If you install electrum rust server later, like I did, you not only need to wait another multiple hours for indexing, but also restart the pi, otherwise mempool won't talk to electrum rust server. (Maybe only mempool service restart would have been sufficient, but I couldn't figure out easily how to do that.)

**Comment by mitohund** [comment]
fwiw I run a RPi4 and have not run into any performance issues at all. And at times I had most services running concurrently (apart from the additional ones for Lightning, since I don't use Lightning).

**Comment by myxmaster** [comment]
Ok good to know, thank you!

**Comment by ExchangeREC** [comment]
> Since I just stumbled upon this again, here's an exemplary (totally random) address that always times out on my Raspiblitz: https://mempool.space/de/address/bc1q9s2kmdhn8xt0qjuks0faetq76ycq7zvq4jdfwf

I can confirm this for the mentioned example address as well! Others with not that much transaction work. Using 1.8.0.c image with Electrs and Mempool.space

**Comment by myxmaster** [comment]
@mitohund 
I guess it's totally normal to run into problems if you lookup addresses with lots of transactions on weak hardware, even if you use lightweight electrum server (electrs). If it is important for you, you might try fulcrum as backend, see this comment: https://github.com/mempool/mempool/issues/1612#issuecomment-1120346897

**Comment by mitohund** [comment]
@myxmaster I only posted that particular address as an extreme case. Issues start earlier, with way fewer transactions.

However, I agree that if the hardware is too weak, I can totally live with the current "limitations". Maybe an info screen with regards to this, when installing mempool.space, would help. Otherwise people end up looking for solutions for a while before they end up in this thread. Personally, I thought there was a problem with my Raspiblitz and I spent quite a while trying to fix it.

Otherwise, if Fulcrum is more performant, maybe that is an option to implement instead of electrs? I of course have no idea how much work that would be and if there would be other upsides and downsides to this. As I said, I can totally live with the current situation, now that I understand it and know that it's not related to an issue with my Raspiblitz.

**Comment by rootzoll** [comment]
@openoms recheck if still relevant

**Comment by chuegel** [comment]
I'm also facing this issue with:
Raspiblitz  1.11.1
Fulcrum 1.10.0

installed on a Pi4 with 8GB RAM

**Comment by rootzoll** [comment]
@openoms was mempool+fulcrum ever tested?
