### ISSUE TITLE
After reboot will not connect to WIFI

### ISSUE THREAD

**Issue by gehrlein** [raspiblitz/raspiblitz#377]
When running the Raspiblitz over WIFI it displays many times after reboot "Waiting for Network ... Not able to get local IP. Is LAN cable connected?"

After a simple reboot by unplugging the energy it works.

**Comment by rootzoll** [comment]
This screen happen when the RaspiBlitz cannot determine its local ip with the following command:
`localip=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1 -d'/')`
But its a waiting loop and and will retry every x seconds. So normally it should continue as soon it gets a localIP. If you run again into that state, please try to SSH into the RaspiBlitz, CTRL+C to the terminal and post the output of the following two commands to this issue so that I can check if maybe that method is not flexible enough:

`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1 -d'/'`

`ip addr`

**Comment by gehrlein** [comment]
Thanks for your answer, the issue is that I run the RaspiBlitz solely over WIFI and therefore I have no option to connect via ssh then. I think I also waited a decent time and it did not work.
Once I got the issue again I can check more things (like if the device is listed under my router) and maybe wait some more.

**Comment by philbertw4** [comment]
For what it's worth, I have run into this as well multiple times, including just today. Probably anyone who runs their blitz over wifi will run into this if they forget to put a wpa_supplicant.conf file. I tried plugging in keyboard and pressed ctrl+c, ctrl+d, ctrl+z, and anything else I could think of. The pi was in fact registering key strokes (per what was displayed on the LCD), but nothing seemed to break it out.

The only solution that worked was for me to unplug the energy like @gehrlein did. Would be great to know if there is a better workaround.

**Comment by rootzoll** [comment]
if you activate the touchscreen you should have shutdown & restart options - even when WIFI connection gets lost.

**Comment by philbertw4** [comment]
Thanks for the quick reply @rootzoll -- I'm using (at the moment) 1.5.1 and this was on a brand new fresh install. I've since pulled the energy, added the wpa_supplicant.conf file to the sd card and started up again. However, for future reference, can you clarify what you mean by "activate the touchscreen?" It seemed non-responsive when I was touching it and I'm not sure how to activate it when it's stuck in that loop. Thanks again.

**Comment by rootzoll** [comment]
Touchscreen is a feature that needs to be activated once setup is done. In v1.5 its MAINMENU > SERVIVES > Touchscreen ... in future versions it might be activated by default.

**Comment by nyxnor** [comment]
please close this.
