### ISSUE TITLE
Connect to Tor address for LND v1 invoice api

### ISSUE THREAD

**Issue by Godrigos** [raspiblitz/raspiblitz#3982]
Hi there. I'm new to the hole bitcoin universe and as a node owner too (as you will notice by my question).
I've been searching about it and could not find a way to connect to my v1/invoice api on my raspblitz. I have the invoice macaroon HEX, but don't know exactly to what address I should connect. My node address (from 1ml, amboss, etc) doesn't work, as I expected...
Any tip on how I can access this part of the api through Tor? How did I get this hidden service onion address?

I'm on version 1.8.0 (default LND version).

Ps.: for context sake... I'm trying to use [Nostdress](https://lnaddress.com/lnaddress).

Thanks for the attention and time.

**Comment by rootzoll** [comment]
The LND REST API runs on port 8080 on your RaspiBlitz. So if you call on your browser `https://[LOCALIP]:8080/v1/getinfo` you see some response. To keep in min here:

- you need to use `https` because LND is using their own TLS certificate
- that TLS certificate isa self-signed and you might allow that with your browser
- if you get a response LND will give an error back demanding a macaroon

But you you basically see that the LND REST API is available. 

**But what about Tor?** 

For that we need to get the onion address for the LND REST API first - do get that run when SSH in on command line `sudo cat /mnt/hdd/tor/lndrest/hostname` then you will get back an oniionaddress like for example `7hyube57cxcd47lcgrihujaevtsqlgd5ga34l637rgsyvd32xq6da6id.onion` And you can now take that onien address and use it to test call the API in the Tor browser like with:

`https://7hyube57cxcd47lcgrihujaevtsqlgd5ga34l637rgsyvd32xq6da6id.onion:8080/v1/getinfo`
