### ISSUE TITLE
add overcommit_memory to redis config

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#3983]
From the redis logs under `/var/log/redis/redis-server.log`:

```
WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

See also: https://redis.io/docs/management/admin/

**Comment by fusion44** [comment]
I think this only applies if we were persisting the DB to disk, which AFAIK we're not.

**Comment by rootzoll** [comment]
_When overcommit_memory is set to 0 (the default), the kernel uses a heuristic algorithm to determine whether to allow a process to allocate more memory than is available. This can lead to situations where a process is allowed to allocate more memory than is physically available, which can cause the system to become unstable or crash._

_When overcommit_memory is set to 1, the kernel will always allow a process to allocate memory up to the limit of its address space, regardless of how much physical memory is available. This can prevent the system from becoming unstable or crashing due to memory allocation issues, but it can also cause processes to fail if they try to allocate more memory than is available._

To set overcommit_memory=1 seems like the more stable option.

**Comment by rootzoll** [comment]
@openoms can you recommend the changes in #4041

**Comment by openoms** [comment]
Agree, individual processes failing is the less evil. They can restart and allow time to diagnose the memory overallocation problem.

If we can we should add warnings if anything crashes due to OOM (out of memory) events.

**Comment by rootzoll** [comment]
PR merged - now on final testing
