### ISSUE TITLE
unable to make lightning payments over tor

### ISSUE THREAD

**Issue by AlverGant** [raspiblitz/raspiblitz#403]
I have build raspiblitz v1.0, building my own SD card as per installation instructions but after two days trying I am still unable to even make small (15 satoshis) payments, lncli payinvoice just hangs forever.

I had no problems funding raspiblitz, opening payment channels manually, receiving network information through gossip and seeing my node on 1ML.

I am routing through tor however, are there anyone out there with the same problem?

**Comment by AlverGant** [comment]
In order to figure out the problem, I reconfigured raspiblitz to disable tor and set up a Dyn DNS forwarding the relevant ports and rebooting the raspberry. Had to setup new channels and now I am able to make payments. It appears to me that something is wrong with tor routing. 
By the way even after disabling tor under service menu, it is still running "/usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc -f /etc/tor/torrc --RunAsDaemon 0"

**Comment by rootzoll** [comment]
Thanks for the report. First of all I am adding a task ..

TODO: for v1.1 realease - check on the TOR disable

Normally making payments when the node is running on TOR should be possible. That the LND request "just hangs" and is not giving any kind of error message is not a good experience. Please feel free to let the people in LND Dev Slack know - so that can be improved: https://dev.lightning.community

**Comment by nyxnor** [comment]
close this pls.
