### ISSUE TITLE
pin CLBOSS fork for msat compatibilty

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4110]
CLBOSS is not compatible for the latest CLN releases after "msat cleanup".

Will need to test a pending PR and pin it in the install script: https://github.com/ZmnSCPxj/clboss/pull/162

**Comment by chrisguida** [comment]
I've [tested](https://github.com/ZmnSCPxj/clboss/pull/162#issuecomment-1682803646) @ksedgwic's PR with 23.02. If @ZmnSCPxj merges that, then we're good.

If not, that could become the official fork.

Otherwise, changing [this line](https://github.com/raspiblitz/raspiblitz/blob/ebfb13b55dd805455542b60716c4edf3da2b024f/home.admin/config.scripts/cl-plugin.clboss.sh#L50) to `https://github.com/ksedgwic/clboss/archive/update-amounts-to-msat.tar.gz \` works just fine, you'll also need to change `CLBOSSVERSION` to `update-amounts-to-msat` if you want to not have to do this manually.

Also I noticed that the `autoreconf -i` step in the build fails unless you do `sudo apt install autoconf-archive` first.

**Comment by chrisguida** [comment]
[This line](https://github.com/raspiblitz/raspiblitz/blame/ebfb13b55dd805455542b60716c4edf3da2b024f/home.admin/config.scripts/cl-plugin.clboss.sh#L63) is also missing `sudo -u bitcoin autoreconf -i` before the `sudo -u bitcoin ./configure` step

**Comment by openoms** [comment]
We got some merges on the weekend so can build from master: https://github.com/ZmnSCPxj/clboss/commits/master

**Comment by openoms** [comment]
@chrisguida opened #4121 to fix clboss with the latest CLN
realized that it does not work yet on signet, but hoping for https://github.com/ZmnSCPxj/clboss/pull/149 to be merged

**Comment by chrisguida** [comment]
Cool, what does blitz need signet for?

Edit: Ah I see, it's preferred over testnet3 https://github.com/ZmnSCPxj/clboss/pull/149#issuecomment-1685308053

I think all that PR needs is some testing

**Comment by ksedgwic** [comment]
VLS currently uses CLBOSS in testnet to create load for signers under test.  I've wondered what the signet lightning network looked like and if it was better.

mempool.space thinks signet has 35 lightning nodes while testnet shows 470 and mainnet has 15,487

I'm pretty sure signet would require a patch to `min_node_to_process` see https://github.com/ZmnSCPxj/clboss/pull/156/commits/ad494459840ee4b4f5abac0d8cc6f00faba8b776

I'm interested in learning if signet is a viable alternative ...

**Comment by openoms** [comment]
The LN on the default signet is indeed much smaller, but most nodes are functional.
There are many more zombie ones on testnet.

The deciding problem with testnet3 for me is the occasional block storms: https://blog.lopp.net/the-block-storms-of-bitcoins-testnet/ which make bitcoind unusable for a day or so. Last when I caught it: https://twitter.com/openoms/status/1537780122673086464

Here is a list of tools available to move testing to signet: https://dev.galoy.io/docs/signet


It makes sense to make the `min_node_to_process` minimal on signet especially that a custom (even smaller) signet network could also be used. See the Plebnet Playground: https://plebnet.wiki/wiki/Plebnet_Playground or Mutinynet for example: https://blog.mutinywallet.com/mutiny-wallet-signet-release/

**Comment by chrisguida** [comment]
mutinynet.com is also a fantastic signet for testing, as it has 30-second blocktimes.

**Comment by rootzoll** [comment]
Merged #4121 - will be part of v1.10.0rc4. Final testing.
