### ISSUE TITLE
Deactivate Touchscreen and remove from the ssh menu until fixed

### ISSUE THREAD

**Issue by Sigevi** [raspiblitz/raspiblitz#4554]
The Rapsiblitz LCD stays black after final reboot. With ssh it's possible to check out the normal view and everything else. 
I tried to update it again but the same Result came out. 

It worked well with the old version. 

Thanks!

**Comment by milezzz** [comment]
Same issue for me after upgrading to v1.11 (fat). For me it's a black screen with blinking cursor in top corner. I know the screen is working because if I reflash the SDcard I can see proper output to the screen until the final reboot after its setup process.

I tried reloading the driver with ```LCD-show```, also tried from cli: ```lcd```

This is a RaspiBlitz running since 2019 without any issues. Nothing suspicious found after running a bug report.

**Comment by milezzz** [comment]
Doh! Please disregard my post above, I had the screen settings incorrect. Settings below got me back to normal:

![CleanShot 2024-04-27 at 17 47 56@2x](https://github.com/raspiblitz/raspiblitz/assets/2200225/263f1120-e125-4109-85ed-cd2c074eeaf3)

**Comment by openoms** [comment]
Correct, activating the Touchscreen does result in a black screen currently. Should be deactivated until fixed.
