### ISSUE TITLE
Stuck at "Starting RaspiBlitz. Please wait ..." with amd64-lean-legacyboot-image-build 1.11 (#166)

### ISSUE THREAD

**Issue by trumfnator** [raspiblitz/raspiblitz#4555]
I was successfully using a 1.11rc0 amd64-lean-legacyboot build before since Dec '23 thereabout (and a 1.9 amd64 build before that).

I flashed the image like described in https://github.com/raspiblitz/raspiblitz/tree/v1.11/ci

![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/81237e40-74ba-4866-9f2f-2907820964ca)

Stuck at this screen after flashing amd64-lean-legacy-image-build 1.11. on existing 1.11rc0 build (also amd64 lean legacy). Before this screen, there was „background.scan not ready yet ... (please wait)“ repeatably in the terminal.

lsblk shows:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/e454e508-e943-4d6c-887a-50a109d58f20)

df shows:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/d1a8e498-e1d2-43fb-9808-351ce112ce12)

Successfully added hdd to mnt/hdd manually and also updated fstab. Auto mount after reboot:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/4993576c-85b3-4fdb-aaf9-cf2903f104cd)

But I'm still stuck with "background.scan not ready yet ...(please wait)" and the "Starting Raspiblitz Please Wait ..." Screen.

**Comment by DrBlackross** [comment]
i had a hell of a time too, but i finally figured out to flash the img to the main 120gb ssd, downside, i kept having a small root. 
then i finally wiped the ssd completely clean and figured out the partition to expand on my drive in linux (desktop) then for some reason it booted ok. 

also i had to turn off uefi and goto legacy+uefi mode in motherboard settings... thats when it worked with my old /mnt/hdd disk and started restoring but crashed, sooo then i re-did a clean install, waited for it to boot up and re-sync everything and then restored the LND data from the lnd-rescue file, rebooted, now its smooth.... but i lost i2p (dont really care i have tor and ipv4) also for some reason thunderhub will not reinstall or install and run like before.

main page works (lost it a while ago), ride the lighting works, mempool and explorer works too, but itll say thunderhub is installed on the main root webpage and doesnt work lol.

but i am running
               RaspiBlitz v1.11.0  
and it updates on amboss like thunderhub is running (only place i ever saw anything about amboss)
https://amboss.space/node/0282b3650afa7a0853231c5b2aed5da16a969730117541c9896fb7b9ce7d9ba306

i would try installing 1.11 and restore with lnd-rescue under the repair LND menu option... then try patching from inside on the menu in ssh also keep your lnd-recue handy just in case...

OH yea, the other thing i noticed, if you backup your channel data to a usb thumb drive (previously), it requires a bigger thumb drive now, my 8gb wont cut it anymore.

BTW.... yes thunderhub is running just cant access the website since i upgraded to 1.11
(no real loss i have RTL)

● thunderhub.service - ThunderHub daemon
     Loaded: loaded (/etc/systemd/system/thunderhub.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-04-26 14:24:50 EDT; 6s ago
   Main PID: 903735 (npm run start)
      Tasks: 37 (limit: 8211)
     Memory: 254.2M
        CPU: 8.613s
     CGroup: /system.slice/thunderhub.service
             ├─903735 "npm run start"
             ├─903760 sh -c "cross-env NODE_ENV=production nest start"
             ├─903761 node /home/thunderhub/thunderhub/node_modules/.bin/cross-env NODE_ENV=production nest start
             └─903771 node /home/thunderhub/thunderhub/node_modules/.bin/nest start

Apr 26 14:24:50 raspiblitz-amd64 systemd[1]: Started thunderhub.service - ThunderHub daemon.
Apr 26 14:24:51 raspiblitz-amd64 npm[903735]: > thunderhub@0.13.30 start
Apr 26 14:24:51 raspiblitz-amd64 npm[903735]: > cross-env NODE_ENV=production nest start

**Comment by openoms** [comment]
@trumfnator can you please check the output of:
```
sudo /home/admin/config.scripts/blitz.datadrive.sh status
```
It should have:
```
hddRaspiData=1
```
or we need to solve if it gets into some kind of error.

What is your hardware setup exactly? A headless PC with two SATA disks?

**Comment by trumfnator** [comment]
@openoms here is the output:

![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/edbb6d87-433b-4673-bcfb-8a56dd162ff6)

setup is a x220 laptop. WWAN module replaced with m.2-ssd as OS disk and a 1tb ssd for the blockchain data in the regular hard drive slot of the laptop.

edit:
btrfs-progs is indeed not installed:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/7902cfc3-d751-41d9-9f9a-430123204019)

edit2:
ps aux | grep -i apt gives:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/a48543c2-674f-4555-8128-417476b4bc5f)

So, the script gets stuck installing the btrfs-progs package?

edit:
I tried to stop the process locking the apt-get command. But it gets restarted every time.

**Comment by trumfnator** [comment]
Nevermind, I could kill the process in the end and could use apt-get on my own, but i couldn't install btrfs-progs:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/32455364/3a27aca2-ffdd-409b-806d-6b9c3033a99c)

**Comment by trumfnator** [comment]
Okay, I will close this issue.

Source of problem was a DNS Server issue on my part.

**Comment by openoms** [comment]
Great, thank you for documenting the issue.

**Comment by 314159-r** [comment]
But now I'm having the same issue, but with a Raspberry Pi 4, trying to upgrade from 1.10.0 to 1.11.0.
First boot get stuck, trying to install btrfs-progs, fails and loops infinitely.

I tried the command: `sudo /home/admin/config.scripts/blitz.datadrive.sh status`
a few times and got:
```
# raspi_bootdir(/boot/firmware)
# Installing BTRFS ...
E: Failed to fetch http://deb.debian.org/debian/pool/main/b/btrfs-progs/btrfs-progs_6.2-1_arm64.deb  404  Not Found [IP: 151.101.86.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error='missing btrfs package'
```
In my case it's not a DNS issue.
Browsing to `http://deb.debian.org/debian/pool/main/b/btrfs-progs` shows a long list of btrfs packages, but not this one. And I can use wget in raspiblitz to fetch http://deb.debian.org/debian/pool/main/b/btrfs-progs/btrfs-progs_6.2-1+deb12u1.dsc. 

The requested packet is simply missing...

Can I skip one or several versions when upgrading, and jump from 1.10.0 to 1.11.2 or 1.11.3 ?

**Comment by rootzoll** [comment]
@314159-r try latest v1.11.3 image - if I remember correctly it checks for BTRFS now a different way.

**Comment by 314159-r** [comment]
Yes, that worked! 
Upgrading from v1.10.0 to v1.11.3 completed without issues. I'm up and running... 

And thank you for responding to this old closed issue. I hesitated to post here, but the the issue description by @trumfnator matched mine perfectly, although for another reason.

**Comment by 314159-r** [comment]
...well, the upgrade completed... but it wiped my LNbits setup clean!
All users, wallets and settings are gone. 

Luckily for me, I had no funding in there. So the only harm is the loss of some experimental configuration. Instead I get a new opportunity to explore LNbits. For example: Learn how to backup...

I assume this is caused by me skipping versions, and jumping straight to v1.11.3. LNbis appear to have got some substantial development lately. _(In hindsight, I should probably have opted for a minimal jump in version, and start to try with v1.11.1, v1.11.2 and so on, coming from v1.10.0)_.

Or -  Possibly, during my first upgrading attempt, my SD-card died. The node had been unstable some week before, which triggered my upgrade. I had to flash a new card with a fresh v1.10.0, and use that to initiate the upgrade. 
And - I haven't used my LNbits for probably half a year, so I don't really know when it happened...
