### ISSUE TITLE
[v1.11.3] Upon version upgrade prior to final reboot, device does not turn itself off

### ISSUE THREAD

**Issue by henkisdabro** [raspiblitz/raspiblitz#4841]
After flashing the latest version v1.11.3 onto a different SD-card, and running the upgrade process on the raspi, the first parts of the upgrade go well. Before the final reboot (prior to entering password C again, and the "Node is Syncing" step), the instructions via SSH say that "it will perform the reboot, and the screen will turn WHITE and LEDS will stop". This never happens - instead there are error messages on the raspi screen saying that the "stopping the Watchdog has failed" (can't remember the exacts unfortunately), leading me to needing to pull the power plug without seeing the "white screen" as was instructed. The upgrade seems to work thereafter, I've now entered password C and the Node is Syncing (phew) :-)

**Comment by rootzoll** [comment]
I am cloing your issue, because there is already #4534 open addressing it.

But in short: This error seems to occur with RaspberryPi4 since the RaspiOS (which RaspiBlitz is build on) was upgraded to also work with RaspberryPi5 (where this error does not occur). We havent found a way to fix this from the RaspiBlitz side yet. Maybe this goes away with a future RaspiOS update that furure RaspiBlitz versions will build on .. but for now, you need to power-reset (plug power off & on) your RaspiBlitz for now to finalize the reboot if you see this error.
