### ISSUE TITLE
is the lnd cipher seed, also the seed to restore the on chain btc wallet

### ISSUE THREAD

**Issue by coinicarus** [raspiblitz/raspiblitz#580]
This isnt an issue as more of a question, is the LND 24 word cipher seed the way you restore the on chain wallet? if not how do you generate the seed for the on chain wallet? 
thank you!

**Comment by geco91** [comment]
See FAQ on how to recover funds from the RaspiBlitz and the role the seed words play in that:
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-can-i-recover-my-coins-from-a-failing-raspiblitz

I recommend this issue to close.

**Comment by zuardi** [comment]
Thats not what he asked. I believe he is asking how to import his LND wallet into a BIP-39 wallet, transforming his lnd-24 word seed into bip39 24 words seed.

**Comment by coinicarus** [comment]
so essentially I F*d up. I thought(mistakenly) that 24 word seed generated when setting up lnd was my 24word seed for the on chain BTC wallet(i am totally wrong) so now i have a certain amount of BTC 'lost' and the only thing i have is that 24 word LND cipher seed. I had checked the FAQ but possibly i missed something.  I tried importing the LND cipher seed into electrum to no avail. i then figured i would try the lightning labs wallet... also to no avail :( I am willing to write this off as a loss but would love to figure out if i can somehow recover the funds. thank you both zuardi & geco91 for your responses this far.

**Comment by zuardi** [comment]
Im pretty much at same situation. My node doesn't work when I try to recover my old wallet (some kind of out of the bounds range error) but works fine with a new wallet.

**Comment by CommanderPoe** [comment]
> The reason is that LND mnemonic is actually aezeed cipher seed, not BIP 39.

The 24 words DO NOT RECOVER either onchain nor offchain funds! In order to recover the funds that once you sent to your lightning wallet you need to have the (walletdb for onchain and channeldb for offchain) directories that are included in the lnd folder. At least this is my personal experience when trying to recover my funds, I only managed to recover them ALL once I imported those 2 directories i stated before.

#278 #536 #500   are very very long thread about the topic and im missing some others. it is worth reading

**Comment by coinicarus** [comment]
thanks for all your help guys, i will check those topics mentioned by commanderPoe

**Comment by lebowski36** [comment]
Are you serious? Every bitcoin wallet I ever used only need's the seed for recovery. The raspiblitz is not on this train? I thought my seed is enough to recover any onchain funds?

**Comment by openoms** [comment]
>Are you serious? Every bitcoin wallet I ever used only need's the seed for recovery. The raspiblitz is not on this train? I thought my seed is enough to recover any onchain funds?

@lebowski36 The RaspiBlitz is not a bitcoin wallet. It is collection helper scripts running LND on top of Bitcoin Core, which works differently because of the added complexity of the Lightning Network. LND is very much in the beta state despite the Lightning Network growing quickly. It works already quite reliably, but there still some things which are not as intuitive as anyone would like.
