### ISSUE TITLE
Bug: /home/admin/00mainMenu.sh: line 119: lnchannels: command not found

### ISSUE THREAD

**Issue by Smiggel** [raspiblitz/raspiblitz#581]
I get the error from the title when I try to display my lightning balance using the admin menu.

I recently restored my node and upgraded to the latest version of RaspiBlitz. I back upped my Lightning channels. Then I updated my Node software, let the blockchain sync and then restored my channels and funds.

After the system was back up and running and I wanted to look at the wallet balance, I got that error. Not sure if it's just my installation of has the do with the latest image. I can however watch the balance using Zap, when I connect that wallet. So, no real harm is done, but just notice the menu item does not work.

Result of the software test: https://termbin.com/rp9i

**Comment by bitsam** [comment]
Did you upgrade to Raspiblitz v1.2? I also have this problem on v1.1.

**Comment by fluidvoice** [comment]
It's a known problem.  When you have a problem the first thing to do is search for it, like this...
![Screenshot_2019-05-08_07-59-02](https://user-images.githubusercontent.com/373038/57370927-bbedba00-7167-11e9-9890-7ec640c7d5fa.png)

The workaround until it gets fixed in the Raspiblitz scripts is to run these commands from an SSH terminal command line:


`wget https://stadicus.github.io/RaspiBolt/resources/lnbalance`
`wget https://stadicus.github.io/RaspiBolt/resources/lnchannels`
`chmod +x lnbalance && chmod +x lnchannels`
`sudo cp lnchannels /usr/local/bin && sudo cp lnbalance /usr/local/bin`

**Comment by Smiggel** [comment]
> Did you upgrade to Raspiblitz v1.2? I also have this problem on v1.1.

Yes, I did. I use zap wallet, so it’s not really a problem. But just noticed it.

**Comment by geco91** [comment]
Recommend to add this issue to be fixed in next v1.3 release.

**Comment by rootzoll** [comment]
Listed to be fixed in v1.3 release.

**Comment by rootzoll** [comment]
Fixed for v1.3
