### ISSUE TITLE
[1.2] Status Screen on ssh do not show connected peers when using DynDNS

### ISSUE THREAD

**Issue by PatrickScheich** [raspiblitz/raspiblitz#607]
I have a RaspiBlitz without a LCD so I'm connecting over ssh.
The status screen shows

![image](https://user-images.githubusercontent.com/50054697/57852761-51322380-77e4-11e9-90dd-bd50e424427d.png)

but bitcoin-cli show 21 peers
```
admin@DesertRetreatLN:~ $ bitcoin-cli getpeerinfo | grep -c "id.:"
21
```

**Comment by rootzoll** [comment]
This was a design/UI decision because the dynamic dns takes already all the space in that line and can be long .. so to prevent line breaks peers are not displayed then dynamic dns is active. maybe in the future, when we touchscreen offers possibility to switch between "pages" there can be more info. For now use/activate the RTL webUI for more detailed insight. Closing this issue for now.
