### ISSUE TITLE
Update to v1.3 - possible through auto-update function in main menu?

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#716]
Will an update from v1.2 to v1.3 be possible to do over the update function in the main menu? And if yes, when will an update to v1.3 approximately be possible?

**Comment by rootzoll** [comment]
There will be another release candidate of v1.3 next week. The RC1 is already out (with bugs) see v1.3 branch. 

There will be no auto-update for two reasons. 

1. An update on RaspiBlitz means a all fresh sd card with every update. There is no easy way to auto-update a sd card. Why a complete sd car? Because then we can make such an clean update like for the RaspberryPi4 with v1.3 where you will get a new debian version and have always a known combination of software that is tested - makes debug and support much easier, especially if you are a open source project with limited resources.

2. Any auto-update adds a dependency of a central point. That one point has control to upate then all RaspiBlitzes and install new software on them that can do anything (one ring to rule them all). Sure on a manually update you also trust a central release in some way ... but doing it manually adds a delay and a moment of possible research and due diligence. 

Since v1.2 there is the UPDATE option in the main menu. It will check if there is an update and help you thru the manual update process ... but it will not auto-update any time soon.
