### ISSUE TITLE
Wallet backup service HDD->SD

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#79]
see https://twitter.com/JohnDoeCoin/status/1037237581199671301

**Comment by drunkenclam** [comment]
I'm not sure but there still might be a problem if you reimport a backup with old channel states where you could lose your balance in the channel ("justice will be served").

And "old" backup could mean something like 2 minutes old, because you routed a payment 1 minute ago and your channel balances changed...

**Comment by rootzoll** [comment]
@drunkenclam thats absolutly correct. But first I think its better to have a backup, then having none. There will be no automatic reimport at this point in time. If you want to make use of the backup, thats a decision to be made in every single case. I think its good to have at least the option.

**Comment by rootzoll** [comment]
Here are some more details about a backup solution for LND.
https://gist.github.com/bretton/22f628caffde79390a796e75ea528053

Automatic backup would need stop/restart of LND. Newest RaspiBlitz has auto-unlock feature, but this is a too complicated topic for now - closing the ticket. Its better to see if any features from LND come up in the near future and run with those.
