### ISSUE TITLE
make touch/pen useable on command line “UI” 

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#83]
source: https://www.raspberrypi.org/forums/viewtopic.php?p=839857

It would be a better usability if the pen/touch displays could be used like a simple POS without an ssh connection or full keyboard.

**Comment by rootzoll** [comment]
That would one way to go, but maybe not the best time investment. 

Because 1) i would like to change the LCD in the future to a ePaper HAT like this (no touch, but buttons) and 2) POS should ne done thru a connected mobile device (like smartphone) - much better and secure.

**Comment by vv01f** [comment]
ok, not reasonable for the assumed usecase

**Comment by rootzoll** [comment]
Because this was asked again on twitter:
https://twitter.com/raumi75/status/1099066019899953152

Some more resources if someone likes to dig deeper here and activate touch ... here is the manual of the LCD: https://www.elegoo.com/tutorial/Elegoo%203.5%20inch%20Touch%20Screen%20User%20Manual%20V1.00.2017.10.09.zip
